spring.application.name=diaspo

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/diaspodb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

#Configuration du JWT
app.jwt.secret=aEXajvhrl1QHffsXTnNtIpGbopSgqMtRTk0A3Ef/jG4=
app.jwt.expiration-ms=86400000
